### PR TITLE
fix static file directory on export. Add export tests.

### PR DESCRIPTION
**Pull request by torounit**
Fix no parent directory for foo.jpg on export.

#### project.
+ project/
  + public/
      + index.html
      + __images/foo.jpg__

#### on export.
+ project/
  + dist/
      + index.html
      + __foo.jpg__

### CODE REVIEW

**Comment by cognitom** [comment]
@torounit nice catch. Thank you!

**Comment by cognitom** [comment]
@torounit could you pls add the test for it?
You can add a test to `test/spec.js` like this:
https://github.com/cognitom/felt/blob/v0.3.1/test/spec.js#L145-L156

**Comment by torounit** [comment]
@cognitom OK!
Please wait a litte!

**Comment by torounit** [comment]
@cognitom Tests for subdirectory contents and static export added. 😄

**Comment by cognitom** [comment]
LGTM 👍 
Thank you so much!

**Comment by cognitom** [comment]
felt@v0.3.2 has been released just now 😄 
https://www.npmjs.com/package/felt

**Comment by torounit** [comment]
Thanks!!

**Pull request merged**
