### PR TITLE
opts.update taking string value

### PR DESCRIPTION
**Pull request by ninbryan**
CLI  flag `--update` was read as boolean

I'm not too clear what it does yet.
It would take any string value and assumes the `'once'` condition against `'always'` and `'never'`.
I did not add any checking for acceptable strings

Should there be flags like `--update-always`, `--update-never`, and `--update-once`?

### CODE REVIEW

**Comment by cognitom** [comment]
@ninbryan thank you for pointing it out. You're right! It should have been `String`.

The option `update` controls its caching policy:

- `never`: never generate the (cache) file and return error if cache doesn't exist
- `once`: generate once and reuse it if cache file exists (default)
- `always`: always regenerate the (cache) file

https://github.com/cognitom/felt/blob/v0.3.0/lib/handler.js#L79-L96

**Comment by cognitom** [comment]
I've cherrypicked [your commit](https://github.com/cognitom/felt/pull/21/commits/27f1e7ab7db7380b3622868c59c0b971d8afc435) so I'm closing this PR. Thanks!

**Comment by cognitom** [comment]
Done. Pulished to npm :tada:
https://www.npmjs.com/package/felt

**Comment by ninbryan** [comment]
Awesome! I'm still wrapping my head around the options and hope to use it more often with my group!

**Pull request closed without merging**
